apiVersion: v1
kind: Service
metadata:
  namespace: agentic-rag
  name: agentic-rag-service
spec:
  type: ClusterIP
  selector:
    app: agentic-rag-service
  ports:
    - port: 80
      targetPort: 8000
